title: Cosmology with the WFIRST High Latitude Survey
description: WFIRST Science Investigation Team
google_analytics: Cosmology WFIRST BAO baryonic acoustic oscilation GRS galaxy redshift survey WL weak gravitational lensing weak large-scale structure
show_downloads: true
theme: jekyll-theme-cayman

baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Olivier Dore
  url:        http://olivierdore.net

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
